### ISSUE TITLE
Add rollout callback

### ISSUE THREAD

**Issue by yuki462-b** [IBM/oper8#129]
## Is your feature request related to a problem? Please describe.

Currently `Controller` has two callback functions, `after_deploy` and `after_verify`. They are executed at the end of  [RolloutManager.rollout](https://github.com/IBM/oper8/blob/main/oper8/rollout_manager.py#L235)  when [phase1 (deploy graph)](https://github.com/IBM/oper8/blob/main/oper8/rollout_manager.py#L277) is completed.

However there is no call back implementation (as far as I have searched) that is executed when phase1 is `INCOMPLETE` or `FAILED`.

It would be nice to have a callback function (or functions) that is executed even if phase1 failling/incomplete to implement some follow up actions.

## Additional context

I would like to use this follow up function to implement a progress indicator, i.e. gather the number of completed components from the last rollout result.

**Comment by gabe-l-hart** [comment]
Hi @yuki462-b thanks for this suggestion! I think it would be a great new feature to add. We would welcome a PR if you have the bandwidth to take a first pass. I think it would look something like:

1. Add a new base-class method `after_deploy_unsuccessful` in [Controller](https://github.com/IBM/oper8/blob/main/oper8/controller.py#L131)
2. Call `after_deploy_unsuccessful` from [rollout](https://github.com/IBM/oper8/blob/main/oper8/rollout_manager.py#L304) if `not phase1_complete` and pass the `phase1_failed` value

**Comment by yuki462-b** [comment]
@gabe-l-hart 
Thank you for the advise! I will try to implement this feature.

**Comment by yuki462-b** [comment]
I have implemented this feature and created a PR. Please review if you can 🙏 https://github.com/IBM/oper8/pull/131.

**Comment by yuki462-b** [comment]
@gabe-l-hart 
I have implemented this feature and created a PR. Please review if you can 🙏 https://github.com/IBM/oper8/pull/131.
