### ISSUE TITLE
Add a verify function for Jobs

### ISSUE THREAD

**Issue by pit1sIBM** [IBM/oper8#65]
## Description

As a developer, I want to not have to rewrite a verify function for a Job, so that I can focus on other things 

## Discussion

Speaking with @HonakerM on this, we currently write our own verify checks for most of our resources and noticed oper8 provides some of this OOTB for Deployments, Statefulsets, and pods. 

So opening this issue (and a PR) to add a check for Jobs using the same condition mechanism that happens in those checks

## Acceptance Criteria

- [x] Unit tests cover new/changed code
- [ ] Examples build against new/changed code
- [ ] READMEs are updated
- [ ] Type of [semantic version](https://semver.org/) change is identified

**Comment by gabe-l-hart** [comment]
Addressed in #64
